python case_1.py ./LS_Group16/ Class1.txt Class2.txt Class3.txt
python case_2.py ./LS_Group16/ Class1.txt Class2.txt Class3.txt
python case_3.py ./LS_Group16/ Class1.txt Class2.txt Class3.txt
python case_4.py ./LS_Group16/ Class1.txt Class2.txt Class3.txt
python case_1.py ./NLS_Group16/ Class1.txt Class2.txt Class3.txt
python case_2.py ./NLS_Group16/ Class1.txt Class2.txt Class3.txt
python case_3.py ./NLS_Group16/ Class1.txt Class2.txt Class3.txt
python case_4.py ./NLS_Group16/ Class1.txt Class2.txt Class3.txt
python case_1.py ./RD_Group16/ Class1.txt Class2.txt Class3.txt
python case_2.py ./RD_Group16/ Class1.txt Class2.txt Class3.txt
python case_3.py ./RD_Group16/ Class1.txt Class2.txt Class3.txt
python case_4.py ./RD_Group16/ Class1.txt Class2.txt Class3.txt